@echo off
cd /d "%~dp0"
echo ^[API GENERATOR^]: Installing aftman tools...
aftman install
echo ^[API GENERATOR^]: Installing wally packages...
wally install
echo ^[API GENERATOR^]: Building generator...
rojo build -o generate.rbxlx
echo ^[API GENERATOR^]: Opening generator in Studio, please refer to the README instructions in Workspace...
start generate.rbxlx