--[[
    Run this command: [   require(game.ReplicatedStorage.Generate)()   ]

    This will generate module scripts in the "Generated" folder in Workspace.
    Each module script contains the source code for the corresponding generated
    file in the "include/generated" directory in the repository. Manually copy
    the source of each module script to the corresponding file in the
    repository.
]]
